config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {}, module: :accounts, path: :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :main do 

  end

  root  :to => redirect('/accounts/sign_in')

  namespace :linebot do
    resources :clinics, only: [], module: :clinics do
      post "webhook", to: "webhook#create"
      resource :event, only: [:show, :edit, :new, :create, :update], controller: :event
      resource :doctor, only: [:show], controller: :doctor
      resources :patients, only: [:show, :new, :create] 
    end
    resources :events
  end

  resources :clinics, only: [], module: :clinics do
    #看診日曆
    resources :events
    namespace :events do
      namespace :selector do
        resources :event_durations, only: [:index, :create]
        resources :line_accounts, only: [:new, :create]
        resources :search_events, only: [:index]
      end
    end

    #病患
    resources :patients
    resources :patients, only: [], module: :patients do
      resource :notification, only: [:create, :destroy], controller: :notification
      resources :events, only: [:index]
      resources :line_sendings, only: [:index]
    end

    #醫生
    resources :doctors
    resources :doctors, only: [], module: :doctors do
      resource :info, only: [:show, :edit, :update], controller: :info
      resource :info, only: [], module: :info do
        resource :photo, only: [:new, :create], controller: :photo
      end
      resources :doctor_durations, only: [:index, :create]
      resources :doctor_services
      resources :doctor_vacations
      resources :doctor_vacations, only: [], module: :doctor_vacations do
        resources :events, only: [:index]
      end
    end

    #診所
    resource :info, only: [:show, :edit, :update], controller: :info
    resource :info, only: [], module: :info do
      resources :clinic_durations, only: [:index, :create]
      resources :clinic_vacations, only: [:index, :new, :create, :update, :destroy]
      resources :clinic_vacations, only: [], module: :clinic_vacations do
        resources :events, only: [:index]
      end
      resources :services, only: [:index, :new, :create, :destroy]
      resource :photo, only: [:new, :create], controller: :photo
    end

    #關鍵字
    namespace :clinic_line do
      resources :keywords
      resources :knowledge_categories
      resources :knowledge_categories, only: [], module: :knowledge_categories do
        resources :knowledges
      end
      resources :systems
      resources :broadcasts
    end
    resources :members
    resources :members, only: [], module: :members do
      resource :photo, only: [:new, :create], controller: :photo
    end

    namespace :lightbox do
      resources :event_notification_schedules, only: [:new, :create]
      resources :clinic_notifications, only: [:index]
    end
    # resources :event_notification_templates, only: [], module: :event_notification_templates do
      # resources :notifications, only: [:create]
    # end
  end

  namespace :admin do
    namespace :dentists do
    	resources :clinics
      resources :clinics, only: [], module: :clinics do
        resource :info, only: [:show, :edit, :update], controller: :info
        resource :line_config, controller: :line_config
        resources :doctors
        resources :doctors, only: [], module: :doctors do
          resource :info, only: [:show, :edit, :update], controller: :info        
          resources :doctor_durations, only: [:index, :show]
          resources :events
        end
        resources :members
        resources :services
        resources :events
        resources :patients
        resources :patients, only: [], module: :patients do
          resource :info, only: [:show, :edit, :update], controller: :info        
          resources :events
        end
        resources :clinic_holidays
      end
    	resources :doctors
      resources :doctors, only: [], module: :doctors do
        resource :info, only: [:show, :edit, :update], controller: :info
        resources :doctor_durations, only: [:index, :show]
        resources :events
      end
    	resources :members
    	resources :events
      resources :booking_events
    	resources :patients
      resources :patients, only: [], module: :patients do
        resource :info, only: [:show, :edit, :update], controller: :info
        resources :events      
      end
    	resources :services
      resources :line_accounts
      namespace :sys do
        resources :sys_holidays
      end
    end
    namespace :dev do
      resources :clinics
      resources :clinics, only: [], module: :clinics do
        resource :info, only: [:show, :edit, :update], controller: :info
        resources :doctors
        resources :doctors, only: [], module: :doctors do
          resource :info, only: [:show, :edit, :update], controller: :info        
          resources :doctor_durations, only: [:index, :show]
          resources :events
        end
        resources :members
        resources :services
        resources :events
        resources :patients
        resources :patients, only: [], module: :patients do
          resource :info, only: [:show, :edit, :update], controller: :info        
          resources :events
        end
        resources :clinic_holidays
      end
      resources :doctors
      resources :doctors, only: [], module: :doctors do
        resource :info, only: [:show, :edit, :update], controller: :info
        resources :doctor_durations, only: [:index, :show]
        resources :events
      end
      resources :members
      resources :events
      resources :booking_events
      resources :patients
      resources :patients, only: [], module: :patients do
        resource :info, only: [:show, :edit, :update], controller: :info
        resources :events      
      end
      resources :services
      resources :line_accounts
      resources :line_accounts, only: [], module: :line_accounts do
        resource :info, only: [:show], controller: :info
        resources :line_sendings
      end
      resource :linebot, only: [:new, :create], controller: :linebot #for linebot test
      get "styles", to: redirect("/admin/dev/style/colors")
      namespace :style do
        resources :colors, only: [:index, :show]
        resources :buttons, only: [:index, :show]
        resources :lightboxes, only: [:index, :show]
        resources :components, only: [:index, :show]
      end
      namespace :notification do
        resources :event_notification_templates
        resources :event_notification_templates, only: [], module: :event_notification_templates do
          resource :info, only: [:show], controller: :info
          resources :notifications
        end
        resources :event_notification_schedules
        resources :event_notification_schedules, only: [], module: :event_notification_schedules do
          resource :info, only: [:show], controller: :info
          resources :notifications
        end
        resources :event_notifications
      end
      namespace :sys do
        resources :sys_logs
      end
    end
  end

end

app/controllers/admin/dentists/clinics/patients/application_controller.rb
class Admin::Dentists::Clinics::Patients::ApplicationController < Admin::Dentists::Clinics::ApplicationController
  before_action {@embedded = 1}
  before_action :find_patient

  def find_patient
    @patient = @clinic.patients.find(params[:patient_id])
  end
end

app/controllers/admin/dentists/clinics/patients/events_controller.rb
class Admin::Dentists::Clinics::Patients::EventsController < Admin::Dentists::Clinics::Patients::ApplicationController
  before_action -> {
    access_config({
      variable_name: "event",
      new_resource: proc { @patient.events.new},
      find_resource: proc { @patient.events.find(params[:id])},
      resource_params: proc { params.require(:event).permit(@event.class.accessable_atts)}
    })
  }

  def index
    @events = @patient.events
    @events = @events.page(params[:page]).per(20)
  end

end

app/controllers/admin/dentists/clinics/patients/info_controller.rb
class Admin::Dentists::Clinics::Patients::InfoController < Admin::Dentists::Clinics::Patients::ApplicationController
  before_action -> {
    access_config({
      variable_name: "patient",
      find_resource: proc { @patient},
      resource_params: proc { params.require(:patient).permit(@patient.class.accessable_atts)}
    })
  }


end

app/controllers/admin/dentists/clinics/patients_controller.rb
class Admin::Dentists::Clinics::PatientsController < Admin::Dentists::Clinics::ApplicationController
  before_action -> {
    access_config({
      variable_name: "patient",
      new_resource: proc { @clinic.patients.new},
      find_resource: proc { @clinic.patients.find(params[:id])},
      resource_params: proc { params.require(:patient).permit(@patient.class.accessable_atts)}
    })
  }

  def index
    @patients = @clinic.patients
    @patients = @patients.page(params[:page]).per(20)
  end

end

app/controllers/admin/dentists/patients/application_controller.rb
class Admin::Dentists::Patients::ApplicationController < Admin::Dentists::ApplicationController
  before_action {@embedded = 1}
  before_action :find_patient

  def find_patient
    @patient = Patient.find(params[:patient_id])
  end
end

app/controllers/admin/dentists/patients/events_controller.rb
class Admin::Dentists::Patients::EventsController < Admin::Dentists::Patients::ApplicationController
  before_action -> {
    access_config({
      variable_name: "event",
      new_resource: proc { @patient.events.new},
      find_resource: proc { @patient.events.find(params[:id])},
      resource_params: proc { params.require(:event).permit(@event.class.accessable_atts)}
    })
  }

  def index
    @events = @patient.events
    @events = @events.page(params[:page]).per(20)
  end

end

app/controllers/admin/dentists/patients/info_controller.rb
class Admin::Dentists::Patients::InfoController < Admin::Dentists::Patients::ApplicationController
  before_action -> {
    access_config({
      variable_name: "patient",
      find_resource: proc { @patient},
      resource_params: proc { params.require(:patient).permit(@patient.class.accessable_atts)}
    })
  }


end

app/controllers/admin/dentists/patients_controller.rb
class Admin::Dentists::PatientsController < Admin::Dentists::ApplicationController
  before_action -> {@embedded = 1}, only: [:show]
  before_action -> {
    access_config({
      variable_name: "patient",
      new_resource: proc { ::Patient.new},
      find_resource: proc { ::Patient.find(params[:id])},
      resource_params: proc { params.require(:patient).permit(Patient.accessable_atts)}
    })
  }

  def index
    @patients = ::Patient.all
    @patients = @patients.page(params[:page]).per(20)
  end

end

app/controllers/admin/dev/clinics/patients/application_controller.rb
class Admin::Dev::Clinics::Patients::ApplicationController < Admin::Dev::Clinics::ApplicationController
  before_action {@embedded = 1}
  before_action :find_patient

  def find_patient
    @patient = @clinic.patients.find(params[:patient_id])
  end
end

app/controllers/admin/dev/clinics/patients/events_controller.rb
class Admin::Dev::Clinics::Patients::EventsController < Admin::Dev::Clinics::Patients::ApplicationController
  before_action -> {
    access_config({
      variable_name: "event",
      new_resource: proc { @patient.events.new},
      find_resource: proc { @patient.events.find(params[:id])},
      resource_params: proc { params.require(:event).permit(@event.class.accessable_atts)}
    })
  }

  def index
    @events = @patient.events
    @events = @events.page(params[:page]).per(20)
  end

end

app/controllers/admin/dev/clinics/patients/info_controller.rb
class Admin::Dev::Clinics::Patients::InfoController < Admin::Dev::Clinics::Patients::ApplicationController
  before_action -> {
    access_config({
      variable_name: "patient",
      find_resource: proc { @patient},
      resource_params: proc { params.require(:patient).permit(@patient.class.accessable_atts)}
    })
  }


end

app/controllers/admin/dev/clinics/patients_controller.rb
class Admin::Dev::Clinics::PatientsController < Admin::Dev::Clinics::ApplicationController
  before_action -> {
    access_config({
      variable_name: "patient",
      new_resource: proc { @clinic.patients.new},
      find_resource: proc { @clinic.patients.find(params[:id])},
      resource_params: proc { params.require(:patient).permit(@patient.class.accessable_atts)}
    })
  }

  def index
    @patients = @clinic.patients
    @patients = @patients.page(params[:page]).per(20)
  end

end

app/controllers/admin/dev/patients/application_controller.rb
class Admin::Dev::Patients::ApplicationController < Admin::Dev::ApplicationController
  before_action {@embedded = 1}
  before_action :find_patient

  def find_patient
    @patient = Patient.find(params[:patient_id])
  end
end

app/controllers/admin/dev/patients/events_controller.rb
class Admin::Dev::Patients::EventsController < Admin::Dev::Patients::ApplicationController
  before_action -> {
    access_config({
      variable_name: "event",
      new_resource: proc { @patient.events.new},
      find_resource: proc { @patient.events.find(params[:id])},
      resource_params: proc { params.require(:event).permit(@event.class.accessable_atts)}
    })
  }

  def index
    @events = @patient.events
    @events = @events.page(params[:page]).per(20)
  end

end

app/controllers/admin/dev/patients/info_controller.rb
class Admin::Dev::Patients::InfoController < Admin::Dev::Patients::ApplicationController
  before_action -> {
    access_config({
      variable_name: "patient",
      find_resource: proc { @patient},
      resource_params: proc { params.require(:patient).permit(@patient.class.accessable_atts)}
    })
  }


end

app/controllers/admin/dev/patients_controller.rb
class Admin::Dev::PatientsController < Admin::Dev::ApplicationController
  before_action -> {@embedded = 1}, only: [:show]
  before_action -> {
    access_config({
      variable_name: "patient",
      new_resource: proc { ::Patient.new},
      find_resource: proc { ::Patient.find(params[:id])},
      resource_params: proc { params.require(:patient).permit(Patient.accessable_atts)}
    })
  }

  def index
    @patients = ::Patient.all
    if params[:name].present?
      @patiens = @patients.where("name like ?", "%#{params[:name]}%")
    end
    if params[:has_line_account].present?
      if params[:has_line_account] == '0'
        ids = @patients.joins(:line_account).pluck(:id)
        @patients = @patients.where.not(id: ids)
      elsif params[:has_line_account] == '1'
        ids = @patients.joins(:line_account).pluck(:id)
        @patients = @patients.where(id: ids)
      end
    end
    @patients = @patients.page(params[:page]).per(20)
  end

end

app/controllers/clinics/patients/application_controller.rb
class ::Clinics::Patients::ApplicationController < ::Clinics::ApplicationController
	before_action :set_patient

	def set_patient
		@patient = @clinic.patients.find_by(id: params[:patient_id])
	end

end

app/controllers/clinics/patients/events_controller.rb
class ::Clinics::Patients::EventsController < ::Clinics::Patients::ApplicationController

	def index
		@events = @patient.events.includes(:service, :doctor).order(:date, :hour, :minute)
	end

end

app/controllers/clinics/patients/line_sendings_controller.rb
class ::Clinics::Patients::LineSendingsController < ::Clinics::Patients::ApplicationController

	def index
		@line_account = @patient.line_account
		@line_sending_messages = @line_account.sending_messages.where(message_type: ["text", "message"]).includes(:sending)
		@line_sending_messages = @line_sending_messages.last(50)
	end

end

app/views/clinics/patients/index/_navbar.html.erb
<div id="show_page_nav">
	<ul>
		<% [
			{name: "病患列表(#{@clinic.patients.count})", link: clinic_patients_path(@clinic), category: "all"},
			{name: "回診推播列表(#{@clinic.clinic_patient_notifications.count})", link: clinic_patients_path(@clinic, category: "notification"), category: "notification"},
			].each do |elm|  %>
		<li class="<%= "selected" if elm[:category] == @category %>">
			<%= link_to elm[:name], elm[:link] %>
		</li>
		<% end %>
	</ul>
</div>

app/views/clinics/patients/index/_pagination.html.erb
<div id="clinic_pagination">
	<%= paginate @patients %>
</div>

app/views/clinics/patients/index/_search_box.html.erb
<div id="search_box">
	<%= form_tag url_for, method: "get" do %>
	<% if @category == "notification" %>
	<%# pushnotificaiton is put at table_box %>
		<%= link_to "javascript: window.pushNotification();", class: "btnW push_notification" do %>
			回診推播(<span class="number">0</span>)
		<% end %>
		<%= select_field_tag "event_notification_status", @event_notification_status, {nil => "選擇訊息發送狀態", 2 => "已約診", 3 => "已取消", 1 => "未回應"}, onchange: "$(this).closest('form').submit();" %>
	<% end %>
	<% if @category == "all" %>
		<%= select_field_tag "has_patient_notification", @has_patient_notification, {nil => "選擇加入推播狀態", 1 => "已加入推播", 0 => "未加入推播"}, onchange: "$(this).closest('form').submit();" %>
	<% end %>
	<div class="input_box">
		<%= hidden_field_tag "category", params[:category] %>
	  <div class="search_box clinic_form_search">
	    <div class="inbox">
	    	<% if params[:key].present? %>
 	    	<span class="close_btn">
	    		<%= link_to icon_tag(:close_circle), url_for %>
	    	</span>
	    	<% end %>
	      <%= text_field_tag "key", params[:key], placeholder: "輸入病患名稱以查詢", class: "clinic_search_input", data: {url: clinic_events_selector_search_events_path(@clinic)} %>
	      <%= hidden_field_tag "event_id", @event.present? ? @event.id : nil %>
	      <%= image_tag clinic_static_image_url(:search) %>
	    </div>
	  </div>
		<%# text_field_tag "key", params[:key], id: "search" %>
		<div class="search_result hidden">
		</div>
	</div>
	<% if @category == "all" %>
	<%= link_to "新增病患", url_for(action: :new), class: "btnBu new_patient" %>
	<% end %>
	<% end %>
</div>

<script type="text/javascript">
	$(function(){
		$("input#search").on("keydown", function(e){
			if(e.keyCode == 13){
				var key = $(this).val();
				if(key.length){
					var path = "<%= url_for %>";
					path = path + "?key=" + key;
					$.getScript(path);
				} else {
					$("#search_box .search_result").html('');
				}				
			}
		});
		$("#search_box").on("click", ".search_result ul li", function(){
			var name = $(this).data("name");
			$("input#search").val(name);
			// $("#search_box .search_result").html('');
			$("#search_box").find('form').submit();
		});
	})
</script>

app/views/clinics/patients/index/_search_result_table.html.erb
<div class="search_result">
	<ul>
	<% @patients.each do |patient| %>
		<li data-name="<%= patient.name %>" data-id="<%= patient.id %>">
			<span><%= patient.name %></span>
			<span><%= patient.gender %></span>
			<span><%= roc_format(patient.birthday, 3) %></span>
			<span><%= patient.person_id %></span>
			<span><%= patient.phone %></span>
		</li>
	<% end %>
	</ul>
</div>

app/views/clinics/patients/index/_table_box.html.erb
<div id="patient_table_box">
  <%= render partial: "clinics/common/clinic_table" , locals: {
    id: "patients",
    class: "",
    resources: @patients,
    cols: proc do 
      r = []
      if @category == "notification"
        r += [
          {t: check_box_tag("", "", false, class: "notification_check_all"), unclickable: true, v: proc{ |a, index| 
              event_notification = a.current_event_notification 
              r = check_box_tag("", "", false, class: "notification_check", data: {patient_id: a.id, args: {clinic_name: @clinic.name, patient_name: a.name}}, disabled: event_notification.present?)
              r.html_safe
            }
          },
          {t: "推播訊息狀態", v: proc { |a|
            event_notification = a.current_event_notification
            if event_notification.present?
              r = "<p> #{event_notification.status} </p>"
              r += "<p class='fs10 colorGy1'> #{roc_format(event_notification.created_at, 3)} 已推播</p>"
              r.html_safe
            end
          }}
        ]
      end
      r += [
        {t: "病患姓名", v: proc{|a| "#{a.name} #{a.id}" }},
        {t: "性別", v: proc{|a| a.gender }},
        {t: "出生年月日", v: proc{|a| roc_format(a.birthday, 3) }},
        {t: "身分證號碼", v: proc{|a| a.person_id }},
        {t: "聯絡電話", v: proc{|a| a.phone }},
        {t: "看診醫生", v: proc{|a|
          if a.default_doctor
            a.default_doctor.name
          else
            ""
          end
        }},
        {t: "已可洗牙", v: proc{|a| 
          if a.available_for_tooth_cleaning 
            icon_tag(:circle, class: 'colorBu')
          else
            ""
          end
        }},
        {t: "下次約診日期", v: proc{|a| a.current_event.try(:date) }},
      ]

      title = @category == "all" ? "加入推播狀態" : "清單加入狀況"
      r += [
        {t: title, unclickable: true, v: proc{|a| 
          render_relative_partial "../common/notification_action", locals: {patient: a}
        }}
      ]
     r
   end.call,
    row: {
      link: proc do |a|
        url_for(action: :show, id: a)
      end
    }
  }
  %>
</div>

<script type="text/javascript">
  $(function(){
    $("#patients_index").on("change", ".notification_check", function(){
      updateChecked(this);
      updateCount();
    });
    $("#patients_index").on("change", ".notification_check_all", function(){
      var checked = this.checked;
      $("#patients_index .notification_check").each(function(i, elm){
        $(elm)[0].checked = checked;
        updateChecked(elm);
      })
      updateCount();
    });

    window.pushNotification = function(){
      var selNotifications = $("#patient_table_box input.notification_check:checked").toArray().map(function(elm){
        var data = $(elm).data();
        return {
          patient_id: data.patientId,
          args: JSON.stringify(data.args)
        }
      });
      $.ajax({
        url: "<%= new_clinic_lightbox_event_notification_schedule_path(@clinic) %>",
        method: "get",
        data: {
          event_notification_schedule: {
            category: "回診推播",
            schedule_type: "立即發送",
            notifications_attributes: selNotifications
          }
        }
      })
    }

    function updateChecked(input){
      var checked = input.checked;
      $(input).siblings().each(function(i, elm){
        elm.checked = checked;
      })
    }

    function updateCount(){
      var count = $("#patients_index .notification_check:checked").length;
      $("#search_box .number").text(count);
    }
  })
</script>

app/views/clinics/patients/index/x_navbar.html.erb
<div id="patients-nav">
	<ul>
		<% [
			{name: "病患列表", link: url_for},
			{name: "回診推播列表", link: url_for(key: "round")},
			].each do |elm|  %>
		<li class="<%= "selected" if request.fullpath == elm[:link] %>">
			<%= link_to elm[:name], elm[:link] %>
		</li>
		<% end %>
	</ul>
</div>